# Generated by Django 4.2.2 on 2024-01-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='id Marca')),
                ('nombreMarca', models.CharField(max_length=80, verbose_name='Nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False, verbose_name='id Modelo')),
                ('nombreModelo', models.CharField(max_length=80, verbose_name='Nombre Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='id producto')),
                ('nombreProducto', models.CharField(max_length=80, verbose_name='Nombre Producto')),
                ('descripcionProducto', models.CharField(max_length=80, verbose_name='Descripcion Producto')),
                ('Precio', models.IntegerField(verbose_name='Precio')),
                ('foto', models.ImageField(default='core/img/logo.png', upload_to='core/img/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.modelo')),
            ],
        ),
    ]
