# Generated by Django 5.0.1 on 2024-02-01 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecategoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecomuna', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreestado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLaboratorio', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreregion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretipopago', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretransporte', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='marca',
            name='idMarca',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='idModelo',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='nombreModelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcionProducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombreProducto',
        ),
        migrations.AddField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaingresoproducto',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenproducto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='numeroserieproducto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='preciounitarioproducto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='productoactivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categoria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombrecliente', models.CharField(max_length=80)),
                ('snombrecliente', models.CharField(blank=True, max_length=80, null=True)),
                ('appaternocliente', models.CharField(max_length=80)),
                ('apmaternocliente', models.CharField(max_length=80)),
                ('direccioncliente', models.CharField(max_length=250)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.laboratorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.laboratorio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionentregapedido', models.CharField(max_length=250)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.region'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idestadoentrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.estadoentrega')),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido')),
                ('idtransporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaventa', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
                ('tipopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tipopago')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.venta'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='nombremodelo',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcionproducto',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreproducto',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
